### ISSUE TITLE
[FEATURE] add batch download with cron and sort by downloads

### ISSUE THREAD

**Issue by zhyph** [xmoosex/poster-setter#63]
# Feature Request

## Feature Type
- [X] UI/Frontend  
- [X] Backend/API  
- [ ] Database  
- [ ] Infrastructure  
- [ ] Documentation  
- [ ] Other (please specify)

## Feature Description

It’d be great to have a feature similar to `AutoDownload`, but for batch processing. The idea is to automatically go through all media items in the server’s libraries and download the most popular (e.g., most downloaded) set for each one — basically the first result from the list.

On the first run, it would grab the top set, save it to the local database, and apply it to the media server like a user normally would. On future runs, if that set’s still the most downloaded, it could just check for updates (like `AutoDownload` does). But if there’s a new “most downloaded” set, it could replace the old one if configured to do so.

This could all be controlled via a simple config option, so it wouldn’t need any frontend changes — though it might be nice to have a manual trigger button in the UI with a cooldown to avoid overusing it.

## Use Case

Right now, if I want to download poster sets for everything in my media library, I have to do it one by one — which takes forever. This feature would automate that whole process, making it easier to bulk populate my server. And if required, it's always possible to tweak things later if needed.

## Proposed Solution

Here’s a rough idea of how it could look in the config:

```yaml
DownloadAll:
  Enabled: true          # Turn it on or off
  Cron: '0 0 * * *'      # Optional schedule — maybe enforce a 12h or 24h minimum to avoid abuse
  ForceUpdate: true      # Replace an existing set if a new one becomes more popular
````

When this is enabled, it just runs through everything in the libraries, grabs the top set for each item, and applies it.

## Alternatives Considered

The only real alternative is doing all of this manually — which is super time-consuming. If this fits within how AURA and the Mediux API are meant to work, it’d be an awesome quality-of-life improvement.

Thanks.
